// <auto-generated />
using Kradis.Domain.Discord.Repository.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kradis.Migrations
{
    [DbContext(typeof(MySqlGuildDbContext))]
    [Migration("20260903054454_InitialGuild")]
    partial class InitialGuild
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kradis.Domain.Discord.Repository.Model.GuildModel", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(36)");

                    b.Property<ulong?>("AntiSpamChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("guilds", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
